### ISSUE TITLE
Installation problem with melpa

### ISSUE THREAD

**Issue by jinyangustc** [coldnew/org-ioslide#18]
Using melpa to install the package:
```
M-x package-install ox-ioslide
```
And add `(require 'ox-ioslide)` in the init.el file.
Then what I found in the `ox-ioslide-20150212.407` folder are just some `.el` files:
```
ox-ioslide-autoloads.el
ox-ioslide-helper.el
ox-ioslide-helper.elc
ox-ioslide-pkg.el
ox-ioslide.el
ox-ioslide.elc
```
If I export a org to the slide, I got warning saying that can't find `js/` folder in the  `ox-ioslide-20150212.407` 

Then I tried `git clone` which works perfectly. I can see that the `melpa` just installed some elisp files and no js files was installed. That should be the probelm.

Did I do something wrong in the installation or the `melpa` installation is broken?

**Comment by kuanyui** [comment]
I guess it's because the [recipe on MELPA](https://github.com/milkypostman/melpa/blob/master/recipes/ox-ioslide) lacks of `:files` specified.
By default, MELPA just retrieve `:files ("*.el")`.

**Comment by jinyangustc** [comment]
Thank you for your fix! I'm new to emacs and your comment helps me to understand the mechanism. I'll test it again when your fix is merged. @kuanyui

**Comment by kuanyui** [comment]
Hmmm... But this "mechanism" should be useless at all unless you're going to publish an Emacs package you written =w="

**Comment by jinyangustc** [comment]
Maybe sometime later. Or at least I can get involved in the community. :P

**Comment by coldnew** [comment]
@jinyangustc  The missing files should be installed by melpa now. Can you help me to test it ?

**Comment by jinyangustc** [comment]
Sure.

**Comment by jinyangustc** [comment]
Yes. The installation by mepla is good now.
