### ISSUE TITLE
"../theme/css/small-icon.css" not found

### ISSUE THREAD

**Issue by AndrewBarfield** [coldnew/org-ioslide#25]
I didn't see anything wrong on-screen, but this error was found in Chrome's console:

Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/U406151/Downloads/org-ioslide-master/example/theme/css/small-icon.css

**Comment by coldnew** [comment]
seems like I forget to commit the generate file (small-icon.css) in example folder, I'll fix it up.

ps: you can fetch the file here: https://github.com/coldnew/org-ioslide/blob/gh-pages/theme/css/small-icon.css
