### ISSUE TITLE
Are there plans to support IE?

### ISSUE THREAD

**Issue by AndrewBarfield** [coldnew/org-ioslide#27]
"Internet Error" versions 8 through 11 don't play well with the slides. Are there plans to support it in the future?

![capture](https://cloud.githubusercontent.com/assets/1271409/7252534/f06b4a00-e803-11e4-89e1-adb955702cfd.PNG)

**Comment by kuanyui** [comment]
![how to tell html5 from html](https://cloud.githubusercontent.com/assets/1370070/7255033/4c698ec8-e879-11e4-9834-62f538543e26.jpg)

**Comment by AndrewBarfield** [comment]
Very true! I think I'll use these slides at work to force my team (to a small degree) to use other browsers.
