### ISSUE TITLE
wrong number of arguments when using `export-to-html`

### ISSUE THREAD

**Issue by Trevoke** [coldnew/org-ioslide#30]
This happens when I call `org-ioslide-export-to-html`
>
org-export-as: Wrong number of arguments: #[(templates) "ebÆÇÈÆÉ#\\Ê Ë	!Ì=XÍ	
\"ÎÏ	\"	ÎÐ	\"E<ÑÒÎÓ	\"\"WW
BÎÔ	\"bÕÆx`|c)+)*" [record object templates value begin signature nil re-search-forward "{{{[-A-Za-z0-9_]" t ...] 6 ("/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.10/share/emacs/24.5/lisp/org/org-macro.elc" . 3797)], 3

Using org-version 8.2.10

**Comment by coldnew** [comment]
Can you share your org file ? I can't reproduce this issue. with emacs 25.0.50.1 and org-mode 8.2.10

Following are mine emacs & org-mode version info:

GNU Emacs 25.0.50.1
 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F27)) of 2015-09-05

Org-mode version 8.2.10
 (8.2.10-41-g42228a-elpaplus @ /Users/coldnew/.emacs.d/.cask/25.0.50.1/elpa/org-plus-contrib-20150622/)

**Comment by Trevoke** [comment]
Hmm.
This now works on both machines where it was broken. I cannot reproduce the problem. Sorry for the false report.

Thank you for providing this package, it is immensely useful!
