### ISSUE TITLE
FR: Make theme configurable

### ISSUE THREAD

**Issue by zakkak** [coldnew/org-ioslide#36]
Hi @coldnew ,

Thanks for this great exporter.

How hard would it be to add an attribute like `#+THEME` to enable choosing a theme from a list of available themes in `/theme/css`?

For instance, for:
```
#+THEME:io2013
```
the presentation should load the `io2013.css` stylesheet.

**Comment by coldnew** [comment]
@zakkak Seems like it can be done. I'll handle it today :)

**Comment by coldnew** [comment]
Now you can use `#+THEME: io2013` to set the default theme to `theme/css/io2013.css`.

**Comment by zakkak** [comment]
Cool, thanks!
