### ISSUE TITLE
apply: Wrong type argument: listp, #("AuthorName" 0 13 (:parent (#0)))

### ISSUE THREAD

**Issue by AdrieanKhisbe** [coldnew/org-ioslide#39]
I'm just trying for the first tome to export using `org-oslide` but I get the following error

    apply: Wrong type argument: listp, #("AdrieanKhisbe" 0 13 (:parent (#0)))

Here is the head of the file:

```org
#+TITLE: Hello Slides
#+SUBTITLE: Draft of ioslide slide
#+DATE: 2015/11/30 02:20
#+AUTHOR: AdrieanKhisbe
#+EMAIL: adrien.becchis@adotmob.com
```

- emacs version: "24.5.1"
- Org-mode version 8.3.2 (8.3.2-37-gd45217-elpa @ /Users/abecchis/.emacs.d_prelude/elpa/org-20151116/)

(I have a similar error with the example file)

**Comment by kuanyui** [comment]
I guess your org-mode installed from ELPA conflicts with build-in one. Remove the ELPA one, restart your Emacs and try again?

**Comment by AdrieanKhisbe** [comment]
Indeed. That works! :)

**Comment by AdrieanKhisbe** [comment]
that was more a problem with my spacemacs config, 
sorry  for that :)
