### ISSUE TITLE
Symbol’s function definition is void: org-html-format-headline--wrapp

### ISSUE THREAD

**Issue by el3ctron** [coldnew/org-ioslide#49]
using GNU Emacs 25.1.50.2 (i686-pc-linux-gnu, GTK+ Version 3.10.8)

when traying to export appears 

`Symbol’s function definition is void: org-html-format-headline--wrapp`

and process stops. without exported html.

**Comment by coldnew** [comment]
Do you know the org-mode version you use ? You can find it by using `M-x org-version`

**Comment by coldnew** [comment]
Hmm... after google it, maybe you use org-mode 8.3, here are related issue for other org-mode exporter:

https://github.com/yjwen/org-reveal/issues/102
https://github.com/kinjo/org-impress-js.el/issues/7

I'll take a look at it

**Comment by coldnew** [comment]
I can't reproduce this issue on org-mode `8.3.6 (8.3.6-7-g4d7d52-elpa)` or `8.2.10 (release_8.2.10)`.

Need to find a way to reproduce it :(

**Comment by el3ctron** [comment]
org-version 8.3.6-3-gf46b92 elpa version

**Comment by el3ctron** [comment]
i try to uninstall and reload the package and now is already running! thanks for your help
